#!/usr/bin/env bash

# curl -O -L https://raw.githubusercontent.com/RayZ0rr/LinuxBootstrap/main/Arch/extra/btrfsLuks2_commands

deviceName="/dev/vda"

SingleCommand() {
cryptsetup open ${deviceName}3 Cbtrfs --key-file mykeyfile.bin && \
  mkfs.fat -F 32 -n part_efi ${deviceName}1 && \
  mkfs.ext4 -L part_boot ${deviceName}2 && \
  mkfs.btrfs -L part_btrfs /dev/mapper/Cbtrfs && \
  mount /dev/mapper/Cbtrfs /mnt && \
  btrfs sub cr /mnt/@ && \
  btrfs sub cr /mnt/@home && \
  btrfs sub cr /mnt/@var_log && \
  btrfs sub cr /mnt/@var_cache && \
  btrfs sub cr /mnt/@snapshots && \
  btrfs sub cr /mnt/@swap && \
  umount /mnt && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@ /dev/mapper/Cbtrfs /mnt && \
  mkdir -p /mnt/{boot,efi,home,var/log,var/cache,.snapshots,root/btrfs-top-level,swap_part} && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@home /dev/mapper/Cbtrfs /mnt/home && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_log /dev/mapper/Cbtrfs /mnt/var/log && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_cache /dev/mapper/Cbtrfs /mnt/var/cache && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@snapshots /dev/mapper/Cbtrfs /mnt/.snapshots && \
  mount -o defaults,ssd,subvol=@swap /dev/mapper/Cbtrfs /mnt/swap_part && \
  mount -o noauto,noatime,defaults,ssd,subvol=/ /dev/mapper/Cbtrfs /mnt/root/btrfs-top-level && \
  mount ${deviceName}1 /mnt/efi && \
  mount ${deviceName}2 /mnt/boot && \
  pacstrap /mnt base linux-lts linux-firmware git vim refind nvidia-lts intel-ucode && \
  genfstab -U /mnt >> /mnt/etc/fstab && \
  mkdir /mnt/root && \
  mv mykeyfile.bin /mnt/root/ && \
  arch-chroot /mnt
}

MultiCommands() {
cryptsetup open ${deviceName}3 Cbtrfs --key-file mykeyfile.bin &&

mkfs.fat -F 32 -n part_efi ${deviceName}1 &&
mkfs.ext4 -L part_boot ${deviceName}2 &&

mkfs.btrfs -L part_btrfs /dev/mapper/Cbtrfs &&
mount /dev/mapper/Cbtrfs /mnt &&

btrfs sub cr /mnt/@ &&
btrfs sub cr /mnt/@home &&
btrfs sub cr /mnt/@var_log &&
btrfs sub cr /mnt/@var_cache &&
btrfs sub cr /mnt/@snapshots &&
btrfs sub cr /mnt/@swap &&
umount /mnt &&

mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@ /dev/mapper/Cbtrfs /mnt &&
mkdir -p /mnt/{boot,efi,home,var/log,var/cache,.snapshots,root/btrfs-top-level,swap_part} &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@home /dev/mapper/Cbtrfs /mnt/home &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_log /dev/mapper/Cbtrfs /mnt/var/log &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_cache /dev/mapper/Cbtrfs /mnt/var/cache &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@snapshots /dev/mapper/Cbtrfs /mnt/.snapshots &&
mount -o defaults,ssd,subvol=@swap /dev/mapper/Cbtrfs /mnt/swap_part &&
mount -o noauto,noatime,defaults,ssd,subvol=/ /dev/mapper/Cbtrfs /mnt/root/btrfs-top-level &&

mount ${deviceName}1 /mnt/efi &&
mount ${deviceName}2 /mnt/boot &&

pacstrap /mnt base linux-lts linux-firmware git vim refind nvidia-lts intel-ucode &&
genfstab -U /mnt >> /mnt/etc/fstab &&
mkdir /mnt/root &&
mv mykeyfile.bin /mnt/root/ &&
arch-chroot /mnt
}

MultiCommands
