#!/usr/bin/env bash

# curl -O -L https://raw.githubusercontent.com/RayZ0rr/LinuxBootstrap/main/Arch/extra/btrfsLuks2_commands
# chmod +x btrfsLuks2_commands

deviceName="/dev/sda"
dev1="${deviceName}1"
dev2="${deviceName}2"
dev3="${deviceName}3"
dev4="${deviceName}4"
deviceMapper="/dev/mapper"
devMapper1="${deviceMapper}/Cbtrfs"
devMapper2="${deviceMapper}/Chome"
part_efi_end="+550MiB"
part_boot_end="+500MiB"
part_root_end="0"

SingleCommand() {
  mkfs.fat -F 32 -n part_efi ${dev1} && \
  mkfs.ext4 -L part_boot ${dev2} && \
  mkfs.btrfs -L part_btrfs ${devMapper1} && \
  mount ${devMapper1} /mnt && \
  btrfs sub cr /mnt/@ && \
  btrfs sub cr /mnt/@home && \
  btrfs sub cr /mnt/@var_log && \
  btrfs sub cr /mnt/@var_cache && \
  btrfs sub cr /mnt/@snapshots && \
  btrfs sub cr /mnt/@swap && \
  umount /mnt && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@ ${devMapper1} /mnt && \
  mkdir -p /mnt/{boot,efi,home,var/log,var/cache,.snapshots,root/btrfs-top-level,swap_part} && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@home ${devMapper1} /mnt/home && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_log ${devMapper1} /mnt/var/log && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_cache ${devMapper1} /mnt/var/cache && \
  mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@snapshots ${devMapper1} /mnt/.snapshots && \
  mount -o defaults,ssd,subvol=@swap ${devMapper1} /mnt/swap_part && \
  mount -o noauto,noatime,defaults,ssd,subvol=/ ${devMapper1} /mnt/root/btrfs-top-level && \
  mount ${deviceName}1 /mnt/efi && \
  mount ${deviceName}2 /mnt/boot && \
  pacstrap /mnt base linux-lts linux-firmware git vim refind nvidia-lts intel-ucode && \
  genfstab -U /mnt >> /mnt/etc/fstab && \
  mkdir -p /mnt/root && \
  mv mykeyfile.bin /mnt/root/
}

Partition_cmnds() {

# Clear all existing partitions and table
sgdisk --zap-all &&
sgdisk --clear &&
sgdisk --align-end &&

# Value 0 means next available space or next available part number
sgdisk -n 0:0:${part_efi_end} -t 0:ef00 -c 0:part_efi "${deviceName}" &&
sgdisk -n 0:0:${part_boot_end} -t 0:8300 -c 0:part_boot "${deviceName}" &&
sgdisk -n 0:0:${part_root_end} -t 0:8300 -c 0:part_root "${deviceName}" &&
# sgdisk -n 1:1:+${part_efi_end} -t 0:ef00 -c 0:part_efi "${deviceName}" &&
# sgdisk -n 2:0:+${part_boot_end} -t 0:ea00 -c 0:part_boot "${deviceName}" &&
# sgdisk -n 3:0:+${part_root_end} -t 0:8300 -c 0:part_root "${deviceName}" &&

# No automount by systemD
sgdisk -A 1:set:63 "${deviceName}" &&
sgdisk -A 2:set:63 "${deviceName}" &&
sgdisk -A 3:set:63 "${deviceName}"

}

Crypt_cmnds() {

cryptsetup luksFormat ${dev3} &&
dd bs=512 count=4 if=/dev/random of=mykeyfile.bin iflag=fullblock &&
chmod 600 mykeyfile.bin &&
cryptsetup luksAddKey ${dev3} mykeyfile.bin &&
cryptsetup open ${dev3} Cbtrfs --key-file mykeyfile.bin

}


Filesystem_cmnds() {

mkfs.fat -F 32 -n label_efi ${deviceName}1 &&
mkfs.ext4 -L label_boot ${deviceName}2 &&
mkfs.btrfs -L label_btrfs ${devMapper1}

}

Mount_cmnds() {

mount ${devMapper1} /mnt &&
btrfs sub cr /mnt/@ &&
btrfs sub cr /mnt/@home &&
btrfs sub cr /mnt/@var_log &&
btrfs sub cr /mnt/@var_cache &&
btrfs sub cr /mnt/@snapshots &&
btrfs sub cr /mnt/@swap &&
umount /mnt &&

mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@ ${devMapper1} /mnt &&
mkdir -p /mnt/{boot,efi,home,var/log,var/cache,.snapshots,root/btrfs-top-level,swap_part} &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@home ${devMapper1} /mnt/home &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_log ${devMapper1} /mnt/var/log &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@var_cache ${devMapper1} /mnt/var/cache &&
mount -o noatime,discard=async,autodefrag,space_cache=v2,ssd,compress=zstd,subvol=@snapshots ${devMapper1} /mnt/.snapshots &&
mount -o defaults,ssd,subvol=@swap ${devMapper1} /mnt/swap_part &&
mount -o noauto,noatime,defaults,ssd,subvol=/ ${devMapper1} /mnt/root/btrfs-top-level &&

mount ${deviceName}1 /mnt/efi &&
mount ${deviceName}2 /mnt/boot

}

Install_cmnds() {

pacstrap /mnt base linux-lts linux-firmware git vim refind nvidia-lts intel-ucode &&
genfstab -U /mnt >> /mnt/etc/fstab &&
mkdir -p /mnt/root &&
mv mykeyfile.bin /mnt/root/

}

Custom_cmnds() {

for arg in "${@}"
do
  if [[ "${arg}" == "partition" ]] ; then
    Partition_cmnds
  elif [[ "${arg}" == "crypt" ]] ; then
    Crypt_cmnds
  elif [[ "${arg}" == "filesystem" ]] ; then
    Filesystem_cmnds
  elif [[ "${arg}" == "mount" ]] ; then
    Mount_cmnds
  elif [[ "${arg}" == "install" ]] ; then
    Install_cmnds
    exit 0
  fi
done

}

case "${1}" in
  "partition")
    Partition_cmnds
    exit 0 ;;
  "crypt")
    Crypt_cmnds
    exit 0 ;;
  "filesystem")
    Filesystem_cmnds
    exit 0 ;;
  "mount")
    Mount_cmnds
    exit 0 ;;
  "install")
    Install_cmnds
    exit 0 ;;
  "all")
    Partition_cmnds &&
    Crypt_cmnds &&
    Filesystem_cmnds &&
    Mount_cmnds &&
    Install_cmnds
    exit 0 ;;
  "custom")
    Custom_cmnds "${@: 2}"
    exit 0 ;;
  *)
    printf "\nNeeds arguments. Available options are 'all,custom,partition,crypt,filesystem,mount,install'.\n\n"
    exit 1 ;;
esac
